### ISSUE TITLE
remove/rethink HEIGHT_INDEX/MORTALITY_INDEX/FECUNDITY_INDEX?

### ISSUE THREAD

**Issue by rafaqz** [traitecoevo/plant#215]
Index order is being defined in two places. It would be good to clean this up somehow using label vectors without any fixed constants.

**Comment by dfalster** [comment]
@johnWilshire recently introduced `get_state` `set_state` methods. These enabled variable numbers of ODEs in the strategies. However, the get/set methods are much slower. 

Having these indexes regains some of the speed loss.  The reason they are implemented for these three variables because every strategy will need to provide at least these 3 variables, so we decided to make them the first 3 in the ODE states & rates.

Happy to rethink.

FYI - I'll be offline the next two days. Feel free to call if there's anything you want to discuss

**Comment by rafaqz** [comment]
I thought there was a reason like that. 

Any getters/setters we swap to would have to compile away to an integer index with no runtime overhead - I don't want to introduce any performance regressions.
