### ISSUE TITLE
Add functions to extract aggregate properties

### ISSUE THREAD

**Issue by dfalster** [traitecoevo/plant#89]
Want to extract important outcome measures at several levels of organisation so that we can compare to data:
- individual plant
- all individuals of given species within a patch of given age
- all individuals of all species within a patch of given age
- average for given species across metapopulation
- average for all species across metapopulation

Desirable outcomes to plot include:
- GPP = photosynthesis 
- NPP = GPP - respiration(maintenance plus growth)
- Dry mass production = NPP - turnover
- Total leaf area
- Stem basal area
- Biomass: above ground (standing, live)
- height: average and top
- seed rain
- seedling density / LAI
- growth, mortality, size distribtions

**Comment by dfalster** [comment]
Ok, i'm revisiting this one now. Have been looking at `run_ebt_collect` function, very nice. How hard would it be to add plant internals to the list? Could we run this with plant plus?

**Comment by richfitz** [comment]
Easy and not so easy.  Probably not realistic for tomorrow.  However, all is not lost.

I need to create a function for going from a Plant -> PlantPlus (#149, and mentioned above).  Then the `ebt_patch` functions can be used to reconstruct plants.

The EBT itself can be templated to run with PlantPlus individuals, but I think that I'd rather reserve that templating for different *Strategy*s, rather than different Plants.

There's no advantage in saving more state with the collector - better to regenerate later I think.

**Comment by richfitz** [comment]
Also requires the densities of cohort and a tool to help integrate that out.  The plant paper does this by hand so getting this done nicely would make that vignette look nicer and be a decent test case.

**Comment by dfalster** [comment]
provisional solution here https://github.com/traitecoevo/plant/commit/748e5c6767d1ae96dc15627de8ac93d5097e5877#diff-04caf0dc54a6175f7b2e7bfb860bc494R444

Let's try it out @aornugent

**Comment by dfalster** [comment]
This is perhaps easier after #308

**Comment by dfalster** [comment]
Achieved via 65da50ab8550436ac32d50817b871903f86d469b
